config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :destroy, :update, :edit, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: :index
  end
  resources :posts, only: [:new, :create, :destroy, :update, :edit, :show]
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true

  belongs_to :author,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs
end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :sub, :post, presence: true
  validates :sub_id, uniqueness: { scope: :post_id }

  belongs_to :post
  belongs_to :sub
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :moderator_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :post_subs
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :session_token, :password_digest, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.is_password?(password)
    nil
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    render :new
  end

  def index
    @posts = Post.all
    render :index
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login(@user)
      redirect_to subs_url
    else
      @user = User.new(user_params)
      flash.now[:error] = ["Invalid credentials"]
      render :new
    end
  end

  def destroy
    logout
    render :new
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def new
    if current_user
      @sub = Sub.new
      render :new
    else
      redirect_to new_session_url
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save!
      redirect_to sub_url(@sub)
    else
      flash[:error] = @sub.errors.full_messages
      redirect_to new_sub_url
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    if current_user.id == @sub.moderator_id
      render :edit
    elsif current_user
      flash[:error] = ["You can't edit this sub!"]
      redirect_to subs_url
    else
      redirect_to new_session_url
    end
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:error] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash[:error] = @user.errors.full_messages
      render :new
    end
  end

  def show
  end

  def destroy
  end

  def edit
  end

  def update
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}' ".html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/errors' %>

<% if current_user %>
  <p>Hi, <%= current_user.username %>!</p>
  <%= button_to("Log out!", session_url, method: :delete) %>
<% else %>
  <%= link_to "Log in!", new_session_url unless request.original_url == new_session_url %>
  <%= link_to "Sign up!", new_user_url unless request.original_url == new_user_url %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts for <%= Sub.find(params[:sub_id]).title %></h1>

<h3> <%= link_to "Make a new post!", new_post_url %></h3>

<ul>
  <% @posts.each do |post| %>
    <li> <%= link_to post.title, post_url(post) %> </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>Create a new post! whatevs..</h1>

<form action="<%= posts_url %>" method="post">

  <%= auth_token %>

  <label for="title">Title: </label>
  <input type="text" name="post[title]">

  <label for="url">URL: </label>
  <input type="text" name="post[url]">

  <label for="content">Content: </label>
  <textarea name="post[content]"></textarea>

  <label for="Subs">Subs</label>
  <input type="hidden" name="post[subs_ids][]">

  <% Sub.all.each do |sub| %>
    <label for="sub"><%= sub.title %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>">
    </label>

  <% end %>

  <input type="submit" value="Submit">

</form>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/shared/_errors.html.erb
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <ul>
      <li><%= error %></li>
    </ul>
  <% end %>
<% end %>

app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

app/views/subs/edit.html.erb
<h1>Edit your sub! whatevs..</h1>

<%= link_to "Return to sub", sub_url(@sub) %>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <%= auth_token %>


  <label for="title">Title: </label>
  <input type="text" name="sub[title]" value="<%= @sub.title %>">

  <label for="description">Description: </label>
  <textarea name="sub[description]"><%= @sub.description %></textarea>

  <input type="submit" value="Edit sub">

</form>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>
  <% @subs.each do |sub| %>
    <li> <%= link_to sub.title, sub_url(sub) %> </li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h1>Create a new sub! whatevs..</h1>

<form action="<%= subs_url %>" method="post">

  <%= auth_token %>

  <label for="title">Title: </label>
  <input type="text" name="sub[title]">

  <label for="description">Description: </label>
  <textarea name="sub[description]"></textarea>

  <input type="submit" value="Submit">

</form>

app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>

<p> <%= @sub.description %> </p>

<section>
  <p><strong> <%= link_to "Create a post!", new_post_url %> </strong></p>
  <ul>
    <% @sub.posts.each do |post| %>
    <li><%= link_to post.title, post_url(post) %></li>
    <% end %>
  </ul>
</section>

<footer>
  <ul>
    <li><%= link_to "Go back to all subs", subs_url %></li>
  </ul>
</footer>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label for="username">Username: </label>
  <input type="text" name="user[username]" id="username" value="<%= @user.username %>">
  <label for="password">Password: </label>
  <input type="password" name="user[password]" id="password">
  <input type="submit" value="Submit">

</form>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>